properties
spring.application.name=SpringBoot_CRUD
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
# ==================== DATABASE CONFIG ====================
# Your MySQL database URL
# localhost = server location
# 3306      = MySQL default port
# studentdb = database name (create this in MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/springboot
spring.datasource.username=root
spring.datasource.password=root
# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ==================== JPA CONFIG ====================
# Hibernate is the JPA implementation Spring Boot uses
spring.jpa.hibernate.ddl-auto=update
# update = auto creates/updates table based on your Entity class
# create = drops and recreates table every restart (data lost)
# create-drop = creates on start, drops on stop
# validate = only validates, doesn't create
# none = do nothing
# Show SQL queries in console (helpful for learning)
spring.jpa.show-sql=true
# Make SQL readable in console
spring.jpa.properties.hibernate.format_sql=true
# Tell Hibernate which database dialect to use
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha